language: python
services:
  - docker
install:
  - travis_retry pip install coveralls
script:
  - docker-compose up test
after_success:
  # Use coverage combine to canonicalize the source paths.
  - coverage combine
  # Upload coverage information to Coveralls.
  - coveralls
